spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://database-1.ch31jk6kzgqo.ap-northeast-2.rds.amazonaws.com/pet?characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/spring
    username: root
    password: ehd5765613
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true


cloud:
  aws:
    s3:
      bucket: kdy-pet
    credentials:
      access-key: AKIAXYAFCWJQMHA3B6HQ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: traced